### ISSUE TITLE
Not compatible with serialport@4.0.1

### ISSUE THREAD

**Issue by bzkdjc** [smart-home-technology/at-commander#1]
Happy to see such a well thought initiative :) 
Yet, I'm using serialport v4 since weeks, and I only get 
**`DEPRECATION: Please use 'require('serialport')' instead of 'require('serialport').SerialPort'`**
at start of my program using this lib and nothing else.

**Comment by tschiemer** [comment]
Hi there!
Hm yes, I also kept getting this message, but admittedly I also kept ignoring it. I'll have a look at it this week, if things go as planned - thanks for pointing it out!

You say you get nothing else? Do you mean that the lib does not work for you?

**Comment by bzkdjc** [comment]
Hi! Thanks for planning to take a look.
The only thing I get from the lib is the `DEPRECATION` warning. My program seems frozen after that message. Nothing happens up to an hour! 
I tried to go back and test my previous program with serialport@4 directly and it worked! 
I didn't check yet to see why I do not get any output from this lib.

**Comment by tschiemer** [comment]
Hi bzkdjc, sorry for the delay, I'm a bit preoccupied at the moment.

Mhm that's strange, I'll try to have a look as soon as possible

**Comment by xtrycatchx** [comment]
encountered the same problem using the following dependencies
```
"serialport": "^4.0.7",
"at-commander": "^1.0.0-beta.4"
```

**Comment by tschiemer** [comment]
I will be releasing a new version these days with some fixes - see current master branch.

I was intending to set the serialport requirement to the latest version 5.0.0. Does would this break your project?

**Comment by donmbelembe** [comment]
This seems not resolved until today

**Comment by tschiemer** [comment]
It was made compatible with v. 5.0.0 . Does this not work for you, or is it rather the build of serialport that fails (as it does for me, aswell as v4.*)? Also see issue #2 

Thus, may I ask, are you requesting compatibility for the latest serialport 7.* or indeed serialport 4.0.1? 

If I'm not very wrong, the latest version of `at-commander` should indeed have fixed the initial bug request, if you have a look at the code.

**Comment by tschiemer** [comment]
w.r.t. serialport 7.*, the parsers have been majorly refactored which would have to be adopted for at-commander, something like:

```

var SerialPort = require('serialport');
const ByteLengthParser = require('@serialport/parser-byte-length')

....

var defaultConfig = {
    parser: new ByteLengthParser({length:1}),
...

```
Whereas you'd have to add the parser as an additional requirement etc.

I'm on the run, thus can not seriously test this, but - apart from other depreciation and unhandled promise warnings - my code fails because it can't open the given serialport. Thus, thus might be a quick fix.
